<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Catalogo extends Model
{
    use HasFactory;
    protected $fillable = ["nombre","descripcion","precio","oferta","imagenes"];

    protected $cast = ['imagenes' => 'array'];
    protected $table = "catalogo";
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function($table){
            if(!app()->runningInConsole()){
                $table->user_id = auth()->id();
            }
        });
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}
